import { IngredientsAndMeasurements } from "./types";

export const ingredientsWithMeasurements: IngredientsAndMeasurements = {
  "'00' Pizza Flour": { cup: 116 },
  "Agave syrup": { cup: 336 },
  "All-Purpose Flour": { cup: 120 },
  "Almond Flour": { cup: 96 },
  "Almond meal": { cup: 84 },
  "Almond paste (packed)": { cup: 259 },
  "Almonds (sliced)": { cup: 86 },
  "Almonds (slivered)": { cup: 114 },
  "Almonds, whole (unblanched)": { cup: 142 },
  "Amaranth flour": { cup: 103 },
  "Apple juice concentrate": { cup: 280 },
  "Apples (dried, diced)": { cup: 85 },
  "Apples (peeled, sliced)": { cup: 113 },
  Applesauce: { cup: 255 },
  "Apricots (dried, diced)": { cup: 128 },
  "Artisan Bread Topping": { cup: 172 },
  "Baker's Special Sugar (superfine sugar, castor sugar)": { cup: 190 },
  "Baking powder": { teaspoon: 4 },
  "Baking soda": { teaspoon: 6 },
  "Bananas (mashed)": { cup: 227 },
  "Barley (cooked)": { cup: 215 },
  "Barley (pearled)": { cup: 213 },
  "Barley flakes": { cup: 92 },
  "Barley flour": { cup: 85 },
  "Barley malt syrup": { tablespoon: 21 },
  "Basil pesto": { tablespoon: 14 },
  "Bell peppers (fresh)": { cup: 142 },
  "Berries (frozen)": { cup: 142 },
  "Cheddar Cheese Powder": { cup: 114 },
  "Blueberries (dried)": { cup: 156 },
  Blueberries: { cup: 140 },
  "Blueberry juice": { cup: 241 },
  "Boiled cider": { cup: 340 },
  "Bran cereal": { cup: 60 },
  "Bread crumbs (dried)": { cup: 112 },
  "Bread crumbs (fresh)": { cup: 84 },
  "Bread crumbs (Japanese Panko)": { cup: 50 },
  "Bread Flour": { cup: 120 },
  "Brown rice (cooked)": { cup: 170 },
  "Brown rice flour": { cup: 128 },
  "Brown sugar (dark or light, packed)": { cup: 213 },
  "Buckwheat (whole)": { cup: 170 },
  "Buckwheat Flour": { cup: 120 },
  Bulgur: { cup: 152 },
  Butter: { tablespoon: 14, stick: 113 },
  Buttermilk: { cup: 227 },
  "Buttermilk powder": { tablespoon: 9 },
  "Cacao nibs": { cup: 120 },
  "Cake Enhancer": { tablespoon: 7 },
  "Candied peel": { cup: 170 },
  'Caramel (14-16 individual pieces, 1" squares)': { cup: 284 },
  "Caramel bits (chopped Heath or toffee)": { cup: 156 },
  "Caraway seeds": { tablespoon: 9 },
  "Carrots (cooked and pureed)": { cup: 256 },
  "Carrots (diced)": { cup: 142 },
  "Carrots (grated)": { cup: 99 },
  "Cashews (chopped)": { cup: 113 },
  "Cashews (whole)": { cup: 113 },
  "Celery (diced)": { cup: 142 },
  "Feta Cheese": { cup: 114 },
  "Grated Cheddar Cheese": { cup: 113 },
  "Grated Jack Cheese": { cup: 113 },
  "Grated Mozzarella Cheese": { cup: 113 },
  "Grated Swiss Cheese": { cup: 113 },
  "Grated Parmesan Cheese": { cup: 100 },
  "Cheese (Ricotta)": { cup: 227 },
  "Cherries (candied)": { cup: 200 },
  "Cherries (dried)": { cup: 142 },
  "Cherries (fresh, pitted, chopped)": { cup: 160 },
  "Cherries (frozen)": { cup: 113 },
  "Cherry Concentrate": { tablespoon: 21 },
  "Chickpea flour": { cup: 85 },
  "Chives (fresh)": { cup: 42 },
  "Chocolate (chopped)": { cup: 170 },
  "Chocolate Chips": { cup: 170 },
  "Chocolate Chunks": { cup: 170 },
  "Cinnamon-Sugar": { cup: 200 },
  "Cocoa Powder (unsweetened)": { cup: 84 },
  "Coconut (sweetened, shredded)": { cup: 85 },
  "Coconut (toasted)": { cup: 85 },
  "Coconut (unsweetened, desiccated)": { cup: 85 },
  "Coconut (unsweetened, large flakes)": { cup: 60 },
  "Coconut (unsweetened, shredded)": { cup: 53 },
  "Coconut cream (unsweetened)": { cup: 284 },
  "Coconut Flour": { cup: 128 },
  "Coconut milk; canned, well shaken": { cup: 241 },
  "Coconut milk (evaporated)": { cup: 242 },
  "Coconut Milk Powder": { cup: 114 },
  "Coconut oil": { cup: 226 },
  "Coconut sugar": { cup: 154 },
  "Confectioners' sugar (unsifted)": { cup: 113.5 },
  "Cookie crumbs": { cup: 85 },
  "Corn (fresh or frozen)": { cup: 152 },
  Popcorn: { cup: 5.25 },
  "Corn syrup": { cup: 312 },
  "Cornmeal (whole)": { cup: 138 },
  "Cornmeal (yellow, Quaker)": { cup: 156 },
  Cornstarch: { cup: 112 },
  "Cracked wheat": { cup: 149 },
  "Cranberries (dried)": { cup: 114 },
  "Cranberries (fresh or frozen)": { cup: 99 },
  "Heavy Cream": { cup: 227 },
  "Half & Half": { cup: 227 },
  "Cream cheese": { cup: 227 },
  "Cream of coconut": { cup: 284 },
  "Creme fraiche": { cup: 248 },
  "Crystallized ginger": { cup: 184 },
  Currants: { cup: 142 },
  "Dates (chopped)": { cup: 149 },
  "Demerara sugar": { cup: 220 },
  "Dried Blueberry Powder": { cup: 112 },
  "Dried milk (Baker's Special Dry Milk)": { cup: 112 },
  "Dried nonfat milk (powdered)": { cup: 112 },
  "Dried potato flakes (instant mashed potatoes)": { cup: 86 },
  "Dried whole milk (powdered)": { cup: 100 },
  "Durum Flour": { cup: 124 },
  "Easy Roll Dough Improver": { tablespoon: 9 },
  "Egg (fresh)": { large: 50, medium: 44, small: 38 },
  "Egg white (fresh)": { large: 35 },
  "Dried egg white": { tablespoon: 5.5 },
  "Egg yolk (fresh)": { large: 14 },
  "Espresso Powder": { tablespoon: 7 },
  "Everything Bagel Topping": { cup: 140 },
  "Figs (dried, chopped)": { cup: 149 },
  "Flax meal": { cup: 100 },
  Flaxseed: { cup: 140 },
  "Fruitcake Fruit Blend": { cup: 120 },
  "Garlic (cloves, in skin for roasting)": { large: 113 },
  "Garlic (minced)": { tablespoon: 14 },
  "Garlic (peeled and sliced)": { cup: 149 },
  Ghee: { cup: 176 },
  "Ginger (fresh, sliced)": { cup: 228 },
  "Gluten-Free '00' Pizza Flour": { cup: 100 },
  "Gluten-Free All-Purpose Baking Mix": { cup: 120 },
  "Gluten-Free All-Purpose Flour": { cup: 156 },
  "Gluten-Free Bread Flour": { cup: 120 },
  "Gluten-Free Measure for Measure Flour": { cup: 120 },
  "Gluten-Free sourdough starter": { cup: 227 },
  "Glutinous rice flour": { cup: 120 },
  "Graham cracker crumbs": { cup: 100 },
  Granola: { cup: 113 },
  "Grape Nuts": { cup: 114 },
  "Harvest Grains Blend": { cup: 148 },
  "Hazelnut flour": { cup: 89 },
  "Hazelnut Praline Paste": { cup: 312 },
  "Hazelnut spread": { cup: 320 },
  "Hazelnuts (whole)": { cup: 142 },
  "Hi-Maize Natural Fiber": { cup: 128 },
  "High-Gluten Flour": { cup: 120 },
  Honey: { tablespoon: 21 },
  "Instant ClearJel": { tablespoon: 11 },
  "Jam or preserves": { cup: 340 },
  "Keto Wheat Flour": { cup: 120 },
  "Keto Wheat Pizza Crust Mix": { cup: 110 },
  "Key Lime Juice": { cup: 227 },
  Lard: { cup: 226 },
  "Leeks (diced)": { cup: 92 },
  "Lemon Crumbles": { cup: 180 },
  "Lemon juice": { tablespoon: 14 },
  "Lemon Juice Powder": { tablespoon: 9 },
  "Lime Juice Powder": { tablespoon: 9 },
  "Macadamia nuts (whole)": { cup: 149 },
  "Malt syrup": { tablespoon: 21.5 },
  "Malted Milk Powder": { cup: 140 },
  "Malted Wheat Flakes": { cup: 128 },
  "Maple sugar": { cup: 156 },
  "Maple syrup": { cup: 312 },
  "Marshmallow spread, homemade": { cup: 72 },
  "Marshmallow spread, store-bought": { cup: 123 },
  "Marshmallow Fluff": { cup: 128 },
  "Marshmallows (mini)": { cup: 43 },
  Marzipan: { cup: 290 },
  "Masa Harina": { cup: 93 },
  "Mascarpone cheese": { cup: 227 },
  "Mashed potatoes": { cup: 213 },
  "Mashed sweet potatoes": { cup: 240 },
  Mayonnaise: { cup: 226 },
  "Meringue powder": { cup: 172 },
  "Milk (evaporated)": { cup: 226 },
  "Milk (fresh)": { cup: 227 },
  "Millet (whole)": { cup: 206 },
  "Mini chocolate chips": { cup: 177 },
  Molasses: { cup: 340 },
  "Mushrooms (sliced)": { cup: 78 },
  "Non-Diastatic Malt Powder": { tablespoon: 9 },
  "Oat bran": { cup: 106 },
  "Oat flour": { cup: 92 },
  "Oats (old-fashioned or quick-cooking)": { cup: 89 },
  "Oats (prepared)": { cup: 147 },
  "Olive oil": { tablespoon: 14 },
  "Olives (sliced)": { cup: 142 },
  "Onions (fresh, diced)": { cup: 142 },
  "Palm shortening": { cup: 180 },
  "Passion fruit puree": { cup: 180 },
  "Pasta Flour Blend": { cup: 145 },
  "Pastry Flour": { cup: 106 },
  "Pastry Flour Blend": { cup: 113 },
  "Peaches (peeled and diced)": { cup: 170 },
  "Peanut butter": { cup: 270 },
  "Peanuts (whole, shelled)": { cup: 142 },
  "Pears (peeled and diced)": { cup: 163 },
  "Pecan Meal": { cup: 80 },
  "Pecans (diced)": { cup: 114 },
  "Pie Filling Enhancer": { cup: 184 },
  "Pine nuts": { cup: 142 },
  "Pineapple (crushed, drained)": { cup: 256 },
  "Pineapple (dried)": { cup: 142 },
  "Pineapple (fresh or canned, diced)": { cup: 170 },
  "Pistachio nuts (shelled)": { cup: 120 },
  "Pistachio Paste": { cup: 312 },
  "Pizza Dough Flavor": { tablespoon: 12 },
  "Pizza Flour Blend": { cup: 124 },
  "Pizza sauce": { cup: 228 },
  "Pizza Seasoning": { tablespoon: 5 },
  "Polenta (coarse ground cornmeal)": { cup: 163 },
  "Poppy seeds": { tablespoon: 9 },
  "Potato Flour": { cup: 184 },
  "Potato starch": { cup: 152 },
  "Pumpernickel Flour": { cup: 106 },
  "Pumpkin puree": { cup: 227 },
  "Quinoa (cooked)": { cup: 184 },
  "Quinoa (whole)": { cup: 177 },
  "Quinoa flour": { cup: 110 },
  Raisins: { cup: 148 },
  "Raspberries (fresh)": { cup: 120 },
  'Rhubarb (sliced, 1/2" slices)': { cup: 120 },
  "Rice (long grain, dry)": { cup: 198 },
  "Rice flour (white)": { cup: 142 },
  "Rice Krispies": { cup: 28 },
  "Rye Bread Improver": { tablespoon: 7 },
  "Rye Chops": { cup: 120 },
  "Rye flakes": { cup: 124 },
  "Rye Flour Blend": { cup: 106 },
  "Kosher Salt, Diamond Crystal": { tablespoon: 8 },
  "Kosher Salt, Morton's": { tablespoon: 16 },
  Salt: { tablespoon: 18 },
  "Sea Salt": { teaspoon: 4 },
  "Scallions (sliced)": { cup: 64 },
  "Self-Rising Flour": { cup: 113 },
  "Semolina Flour": { cup: 163 },
  "Sesame seeds": { cup: 142 },
  "Shallots (peeled and sliced)": { cup: 156 },
  "Six-Grain Blend": { cup: 128 },
  "Sorghum flour": { cup: 138 },
  "Sour cream": { cup: 227 },
  "Sourdough starter": { cup: 227 },
  "Soy flour": { cup: 140 },
  "Sparkling Sugar": { cup: 228 },
  "Spelt Flour": { cup: 99 },
  "Sprouted Wheat Flour": { cup: 113 },
  "Steel cut oats": { cup: 140 },
  "Strawberries (fresh sliced)": { cup: 167 },
  "Sugar (granulated white)": { cup: 198 },
  "Sugar substitute (Splenda)": { cup: 25 },
  "Sundried tomatoes (dry pack)": { cup: 170 },
  "Sunflower seeds": { cup: 140 },
  "Swedish Pearl Sugar": { cup: 196 },
  "Sweet Ground Chocolate and Cocoa Blend": { cup: 112 },
  "Sweetened condensed coconut milk": { cup: 288 },
  "Sweetened condensed milk": { cup: 312 },
  "Tahini paste": { cup: 256 },
  "Tapioca starch or flour": { cup: 113 },
  "Tapioca (quick cooking)": { tablespoon: 10.5 },
  "Teff flour": { cup: 135 },
  "Toasted Almond Flour": { cup: 96 },
  "Toffee chunks": { cup: 156 },
  "Tomato paste": { tablespoon: 29 },
  "Turbinado sugar": { cup: 180 },
  "Cake Flour": { cup: 120 },
  "Vanilla Extract": { tablespoon: 14 },
  "Vegetable oil": { cup: 198 },
  "Vegetable shortening": { cup: 184 },
  "Vital Wheat Gluten": { tablespoon: 9 },
  "Walnuts (chopped)": { cup: 113 },
  "Walnuts (whole)": { cup: 128 },
  Water: { cup: 227 },
  "Wheat berries (red)": { cup: 184 },
  "Wheat bran": { cup: 64 },
  "Wheat germ": { cup: 112 },
  "White Chocolate Chips": { cup: 170 },
  "White Rye Flour": { cup: 106 },
  "White Whole Wheat Flour": { cup: 113 },
  "Whole Wheat Flour": { cup: 113 },
  "Whole Wheat Pastry Flour": { cup: 96 },
  "Graham Flour": { cup: 96 },
  "Yeast (instant)": { teaspoon: 3, packet: 7 },
  "Yeast (active dry)": { teaspoon: 3, packet: 7 },
  Yogurt: { cup: 227 },
  "Zucchini (shredded)": { cup: 121 },
  // Non-KAF
  Vinegar: { tablespoon: 15 },
  "Almond milk": { cup: 240 },
  Bananas: { large: 136, medium: 118, small: 101 },
  Nutella: { tablespoon: 18.5 },
  Biscoff: { tablespoon: 15 },
  Potatoes: { small: 170, medium: 213, large: 369 },
  "Garlic powder": { teaspoon: 3 },
  "Onion powder": { teaspoon: 2 },
  Paprika: { teaspoon: 2 },
  Cinnamon: { teaspoon: 3 },
  Cumin: { teaspoon: 3 },
  "Almond extract": { teaspoon: 5 },
  Mustard: { tablespoon: 16 },
  "Dijon mustard": { teaspoon: 5 },
  Sprinkles: { cup: 160 },
  "Avocado oil": { tablespoon: 14 },
  "Almond butter": { tablespoon: 16 },
  "Lemon zest": { tablespoon: 6 },
};
